# Generated by Django 5.2.4 on 2025-07-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realisation",
            name="media",
        ),
        migrations.RemoveField(
            model_name="realisation",
            name="type",
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(upload_to="realisations_media/")),
                (
                    "type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "realisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="main.realisation",
                    ),
                ),
            ],
        ),
    ]
