# Generated by Django 5.2.4 on 2025-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_realisation_media_remove_realisation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realisation",
            name="image_couverture",
            field=models.ImageField(
                blank=True, null=True, upload_to="realisations_cover/"
            ),
        ),
    ]
