# Generated by Django 5.2.4 on 2025-07-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_realisation_image_couverture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lifestyle",
            name="media",
        ),
        migrations.RemoveField(
            model_name="lifestyle",
            name="type",
        ),
        migrations.AddField(
            model_name="lifestyle",
            name="image_couverture",
            field=models.ImageField(
                blank=True, null=True, upload_to="lifestyle_cover/"
            ),
        ),
        migrations.CreateModel(
            name="LifestyleMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.FileField(upload_to="lifestyle_media/")),
                (
                    "type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "lifestyle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="main.lifestyle",
                    ),
                ),
            ],
        ),
    ]
